/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_xiong_mediarecordertest_MyNative */

#ifndef _Included_com_android_xiong_mediarecordertest_MyNative
#define _Included_com_android_xiong_mediarecordertest_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_xiong_mediarecordertest_MyNative
 * Method:    audioInterface
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_android_xiong_mediarecordertest_MyNative_audioInterface
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_android_xiong_mediarecordertest_MyNative
 * Method:    cToJava
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_android_xiong_mediarecordertest_MyNative_cToJava
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
